services:
  wordpress:
    build: .
    ports:
      - "80:80"
      - "9003:9003" # Xdebug port for PHP debugging
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  # Cron service for reliable WordPress cron execution
  cron:
    image: alpine:latest
    command: >
      sh -c "
        apk add --no-cache curl &&
        echo '# WordPress Cron Jobs (includes Website Monitor Pro)' > /etc/crontabs/root &&
        echo '* * * * * curl -s http://wordpress/wp-cron.php?doing_wp_cron >/dev/null 2>&1' >> /etc/crontabs/root &&
        echo 'WordPress cron service started' &&
        crond -f -l 2
      "
    depends_on:
      - wordpress
    restart: unless-stopped

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: exampleuser
      PMA_PASSWORD: examplepass
    depends_on:
      - db

volumes:
  db_data:
